version: "3.9"
services:
  lb:
    image: nginx:latest
    ports:
      - "2525:2525"
      - "4545:4545"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mb1
      - mb2
      - mb3
  mb1:
    image: bbyars/mountebank:latest
    command: ["--configfile", "/imposters/imposters.json"]
    volumes:
      - ./imposters:/imposters:ro
    ports:
      - "2526:2525"
  mb2:
    image: bbyars/mountebank:latest
    command: ["--configfile", "/imposters/imposters.json"]
    volumes:
      - ./imposters:/imposters:ro
    ports:
      - "2527:2525"
  mb3:
    image: bbyars/mountebank:latest
    command: ["--configfile", "/imposters/imposters.json"]
    volumes:
      - ./imposters:/imposters:ro
    ports:
      - "2528:2525"
